---
title: ""
author: "Yurkov Sergey"
date: "2024-01-01"
categories: [python]
format: html
draft: true
---

In [1]:
%%capture

import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras

print(tf.__version__)

In [2]:
# !unzip archive.zip -n

# import zipfile

# with zipfile.ZipFile("archive.zip", mode="r") as archive:
#     for file in archive.namelist():
#         archive.extractall("archive/")

In [2]:
df = pd.read_csv("archive/labeled.csv", dtype={"toxic": np.int8})

df

                                                 comment  toxic
0                   Верблюдов-то за что? Дебилы, бл...\n      1
1      Хохлы, это отдушина затюканого россиянина, мол...      1
2                              Собаке - собачья смерть\n      1
3      Страницу обнови, дебил. Это тоже не оскорблени...      1
4      тебя не убедил 6-страничный пдф в том, что Скр...      1
...                                                  ...    ...
14407  Вонючий совковый скот прибежал и ноет. А вот и...      1
14408  А кого любить? Гоблина тупорылого что-ли? Или ...      1
14409  Посмотрел Утомленных солнцем 2. И оказалось, ч...      0
14410  КРЫМОТРЕД НАРУШАЕТ ПРАВИЛА РАЗДЕЛА Т.К В НЕМ Н...      1
14411  До сих пор пересматриваю его видео. Орамбо кст...      0

[14412 rows x 2 columns]

In [3]:
# Create data sets for defaults and non-defaults
nondefaults = df[df["toxic"] == 0]
defaults = df[df["toxic"] == 1]

# Undersample the non-defaults
nondefaults_under = nondefaults.sample(len(defaults))

# Concatenate the undersampled nondefaults with defaults
df_balanced = pd.concat(
    [nondefaults_under.reset_index(drop=True), defaults.reset_index(drop=True)], axis=0
)

# Print the value counts for loan status
print(df_balanced["toxic"].value_counts())

toxic
0    4826
1    4826
Name: count, dtype: int64

In [4]:
df_balanced.sample(5)

                                                comment  toxic
1005                     Просто модер такой же куколд\n      1
518   ВО во письмо наверняка хохлы не нравятся видит...      1
2350  А если те кто сидели спереди умерли, да и пере...      0
4715  Тащемта ему могут запросто 5 тысяч за стрим за...      1
3603  Деньги стопудово выделяют. Если нет- главврача...      1

In [5]:
from sklearn.model_selection import train_test_split

X = df_balanced["comment"]
y = df_balanced["toxic"]

y

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, shuffle=True, random_state=0
)

y_train.value_counts()

toxic
0    3888
1    3833
Name: count, dtype: int64

In [11]:
from keras_preprocessing import text

In [12]:
import string

from keras.preprocessing.sequence import pad_sequences
from natasha import Doc, MorphVocab, NewsEmbedding, NewsMorphTagger, Segmenter

segmenter = Segmenter()
morph_vocab = MorphVocab()
emb = NewsEmbedding()
morph_tagger = NewsMorphTagger(emb)

print(morph_vocab)

max_features = 20_000


class RuTokenizer(text.Tokenizer):
    def __init__(self):
        super().__init__(self)

        self.num_words = max_features

    def tokenize(self, text):
        doc = Doc(text)
        doc.segment(segmenter)
        doc.tag_morph(morph_tagger)
        for token in doc.tokens:
            token.lemmatize(morph_vocab)
        # tokens = [_.lemma for _ in doc.tokens if _.text not in string.punctuation]
        tokens = [
            _.lemma.lower()
            for _ in doc.tokens
            if _.text not in string.punctuation
            and len(_.text) > 1
            and not _.text.isnumeric()
        ]

        return tokens


tokenizer = RuTokenizer()
# df_balanced["tokens"] = df_balanced["comment"].apply(
#     lambda x: repr(tokenizer.tokenize(x))
# )
# df_balanced["tokens"]
maxlen = 300
tokenizer.fit_on_texts(X_train)
sequences = tokenizer.texts_to_sequences(X_train)
X_train = pad_sequences(sequences, maxlen=maxlen)

sequences = tokenizer.texts_to_sequences(X_test)
X_test = pad_sequences(sequences, maxlen=maxlen)

model = keras.models.Sequential(
    [
        keras.layers.Embedding(max_features + 1, 128, input_length=maxlen),
        keras.layers.Bidirectional(
            keras.layers.LSTM(
                64, dropout=0.2, recurrent_dropout=0.2, return_sequences=True
            )
        ),
        keras.layers.Bidirectional(
            keras.layers.LSTM(
                64,
                dropout=0.2,
                recurrent_dropout=0.2,
            )
        ),
        keras.layers.Dense(1, activation="sigmoid"),
    ]
)

model.summary()

MorphVocab()

d:\My_Projects\blog\blog\interactive\.venv\lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional (Bidirectional)   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_1 (Bidirectional) │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.compile(keras.optimizers.Adam(0.01), "binary_crossentropy", metrics=["accuracy"])
model.fit(X_train, y_train, batch_size=32, epochs=2, validation_data=(X_test, y_test))

Epoch 1/2
242/242 ━━━━━━━━━━━━━━━━━━━━ 116s 445ms/step - accuracy: 0.6875 - loss: 0.5815 - val_accuracy: 0.8446 - val_loss: 0.3946
Epoch 2/2
242/242 ━━━━━━━━━━━━━━━━━━━━ 105s 432ms/step - accuracy: 0.9409 - loss: 0.1802 - val_accuracy: 0.8457 - val_loss: 0.4060

In [14]:
sequences = tokenizer.texts_to_sequences(["Я хочу есть", "Я люблю тебя"])
test = pad_sequences(sequences, maxlen=maxlen)

output = model.predict(test)

print(output.flatten())

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 777ms/step
[0.17755888 0.9801771 ]

In [15]:
print(sequences)

[[11, 384, 33], [11, 1515, 72]]